apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: cd-binding
spec:
  params:
    - name: repository
      value: "$(body.reposity.url)"
    - name: branch
      value: "$(body.ref)"